import { registerPlugin } from '@wordpress/plugins';
import { PluginSidebar, PluginSidebarMoreMenuItem } from '@wordpress/edit-post';
import { PanelBody, Button, TextareaControl, Notice } from '@wordpress/components';
import { __ } from '@wordpress/i18n';
import { useSelect, useDispatch } from '@wordpress/data';
import { createBlock, getBlockType } from '@wordpress/blocks';
import apiFetch from '@wordpress/api-fetch';
import { useEffect, useMemo, useState } from '@wordpress/element';
import './editor.css';

type Block = { clientId:string; name:string; attributes:Record<string,unknown>; innerBlocks:Block[] };
const ID_RE=/^nd_[a-z0-9]{12,40}$/;
const newId=()=>`nd_${crypto.getRandomValues(new Uint32Array(4)).reduce((s,n)=>s+n.toString(36),'').slice(0,24).padEnd(12,'0')}`;

function normalizeResult(input:string){
 const clean=input.replace(/^\uFEFF/,'').trim();
 const fenced=clean.match(/^```(?:json)?\s*([\s\S]*?)\s*```$/i); return JSON.parse(fenced?fenced[1]:clean);
}
function strip(b:Block):any { return { name:b.name, attributes:b.attributes, innerBlocks:(b.innerBlocks||[]).map(strip) }; }
async function hashTarget(blocks:Block[]){ const raw=JSON.stringify(blocks.map(strip)); const digest=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(raw)); return [...new Uint8Array(digest)].map(x=>x.toString(16).padStart(2,'0')).join(''); }
function collectIds(blocks:Block[], out:string[]=[]){ for(const b of blocks){const id=b.attributes?.noderaId; if(typeof id==='string')out.push(id); collectIds(b.innerBlocks||[],out);} return out; }
function visualCapture(ids:string[]){ const nodes:Record<string,unknown>={}; for(const id of ids){ const el=document.querySelector(`[data-nodera-id="${CSS.escape(id)}"]`) as HTMLElement|null; if(!el) continue; const r=el.getBoundingClientRect(), c=getComputedStyle(el); nodes[id]={rect:{x:r.x,y:r.y,width:r.width,height:r.height},display:c.display,position:c.position,overflowX:c.overflowX,overflowY:c.overflowY,color:c.color,backgroundColor:c.backgroundColor,fontFamily:c.fontFamily,fontSize:c.fontSize,fontWeight:c.fontWeight,lineHeight:c.lineHeight,padding:{top:c.paddingTop,right:c.paddingRight,bottom:c.paddingBottom,left:c.paddingLeft},margin:{top:c.marginTop,right:c.marginRight,bottom:c.marginBottom,left:c.marginLeft},gap:c.gap,flexDirection:c.flexDirection,justifyContent:c.justifyContent,alignItems:c.alignItems,scrollWidth:el.scrollWidth,clientWidth:el.clientWidth,horizontalOverflow:el.scrollWidth>el.clientWidth}; } return {measuredGeometry:Object.keys(nodes).length>0,captureStatus:Object.keys(nodes).length?'ok':'unavailable',viewport:{width:window.innerWidth,height:window.innerHeight,devicePixelRatio:window.devicePixelRatio},nodes}; }

function Sidebar(){
 const [task,setTask]=useState(''); const [result,setResult]=useState(''); const [status,setStatus]=useState<any>(null); const [exported,setExported]=useState<any>(null);
 const { blocks, selected, postId }=useSelect((select:any)=>{ const e=select('core/block-editor'); const ed=select('core/editor'); const id=e.getSelectedBlockClientId(); return {blocks:e.getBlocks() as Block[], selected:id?e.getBlock(id) as Block:null, postId:ed.getCurrentPostId()}; },[]);
 const { updateBlockAttributes, insertBlocks, removeBlock, replaceBlocks, replaceInnerBlocks, moveBlocksToPosition }=useDispatch('core/block-editor') as any;
 useEffect(()=>{ const all:Block[]=[]; const walk=(xs:Block[])=>xs.forEach(b=>{all.push(b);walk(b.innerBlocks||[])}); walk(blocks); const seen=new Set<string>(); for(const b of all){const id=b.attributes?.noderaId as string|undefined; if(!id||!ID_RE.test(id)||seen.has(id)){updateBlockAttributes(b.clientId,{noderaId:newId()});} else seen.add(id);} },[blocks.length]);
 const target=useMemo(()=>selected?[selected]:blocks,[selected,blocks]);
 async function exportContext(){ const ids=collectIds(target); const fingerprint=await hashTarget(target); const catalog:any[]=await apiFetch({path:'/nodera/v1/contracts'}); const ctx={schema:'nodera-ai-context/v1',task:{request:task,mode:selected?'edit':'create'},target:{kind:selected?'subtree':'page',stableIds:ids,fingerprint},document:{scopeTree:target.map(strip)},contracts:{catalogIndex:catalog},visualFacts:{browser:visualCapture(ids)},environment:{noderaVersion:(window as any).NoderaSettings?.version},output:{schema:'nodera-patch/v1'}}; setExported(ctx); await navigator.clipboard?.writeText(`Return nodera-patch/v1 JSON only. Do not edit outside target.\n${JSON.stringify(ctx,null,2)}`); setStatus({type:'success',text:__('AI context copied.','nodera')}); }
 async function validate(){ try{const patch=normalizeResult(result); const response:any=await apiFetch({path:'/nodera/v1/ai/validate',method:'POST',data:{postId,currentBlocks:target.map(strip),editableStableIds:collectIds(target),patch}}); setStatus({type:'success',text:__('Patch validated. Review before applying.','nodera'),response,patch});}catch(e:any){setStatus({type:'error',text:e?.message||__('Validation failed.','nodera')});} }
 function findClient(id:string){let found:string|undefined; const walk=(xs:Block[])=>xs.some(b=>{if(b.attributes?.noderaId===id){found=b.clientId;return true;}return walk(b.innerBlocks||[])});walk(blocks);return found;}
 function materialize(spec:any):any{ const attrs={...(spec.attributes||{})}; if(!attrs.noderaId) attrs.noderaId=newId(); return createBlock(spec.name,attrs,(spec.innerBlocks||[]).map(materialize)); }
 function apply(){ const patch=status?.patch; if(!patch) return; for(const op of patch.operations||[]){const cid=findClient(op.stableId||op.parentStableId); if(!cid) continue; if(op.op==='updateAttributes') updateBlockAttributes(cid,op.attributes||{}); else if(op.op==='removeBlock') removeBlock(cid); else if(op.op==='replaceBlock') replaceBlocks(cid,materialize(op.block)); else if(op.op==='replaceInnerBlocks') replaceInnerBlocks(cid,(op.blocks||[]).map(materialize),false); else if(op.op==='insertBlock') insertBlocks(materialize(op.block),op.index??undefined,cid); else if(op.op==='moveBlock'&&op.toParentStableId){const to=findClient(op.toParentStableId); if(to) moveBlocksToPosition([cid],undefined,to,op.index??0);} } setStatus({type:'success',text:__('Changes applied locally. Save/Update the page to persist them.','nodera')}); }
 return <><PluginSidebarMoreMenuItem target="nodera-ai">{__('Nodera AI','nodera')}</PluginSidebarMoreMenuItem><PluginSidebar name="nodera-ai" title={__('Nodera AI','nodera')}><PanelBody title={__('AI authoring','nodera')} initialOpen><p>{selected?__('Editing selected subtree.','nodera'):__('Editing the whole page.','nodera')}</p><TextareaControl label={__('Task','nodera')} value={task} onChange={setTask}/><Button variant="primary" onClick={exportContext} disabled={!task.trim()}>{__('Copy for AI','nodera')}</Button><TextareaControl label={__('Paste AI result','nodera')} value={result} onChange={setResult}/><Button variant="secondary" onClick={validate} disabled={!result.trim()}>{__('Validate & Preview','nodera')}</Button>{status&&<Notice status={status.type} isDismissible={false}>{status.text}</Notice>}{status?.patch&&<Button variant="primary" onClick={apply}>{__('Apply locally','nodera')}</Button>}<p className="nodera-note">{__('Attach a reference image in your external AI chat when needed.','nodera')}</p></PanelBody></PluginSidebar></>; }
registerPlugin('nodera',{render:Sidebar});
